### ISSUE TITLE
Scores of the FV-encoded IDT descriptors

### ISSUE THREAD

**Issue by carloscaetano** [qijiezhao/Video-Classification-Action-Recognition#1]
Hi,

Could you please provide the SVM scores of the FV-encoded IDT descriptors? My interest is purely for academic purposes.

Thank you in advance.

**Comment by qijiezhao** [comment]
I didn't implement FV-encoded SVM ever. The feature is generated by pretrained CNN

**Comment by carloscaetano** [comment]
Oh, I am so sorry. Wrong Zhao. I am closing the issue.
